// Generated by the WOLips Templateengine Plug-in at Jul 10, 2010 1:13:25 PM
package net.rujel.setup;

import net.rujel.reusables.UTF8Application;

import com.webobjects.foundation.NSLog;

import com.webobjects.appserver.WOApplication;
import com.webobjects.appserver.WORequestHandler;

public class Application extends UTF8Application {
	public static void main(String[] argv) {
		WOApplication.main(argv, Application.class);
	}

	public Application() {
		NSLog.out.appendln("Welcome to " + name() + " !");
		/* ** put your initialization code in here ** */
		WORequestHandler directActionRequestHandler = requestHandlerForKey("wa");
		setDefaultRequestHandler(directActionRequestHandler);
		String ips = (String) System.getProperty("ALLOWED_IPS");
		if (ips != null)
		System.out.println("Allowed IPs: " + ips);
	}
}
