// Generated by the WOLips Templateengine Plug-in at Jul 10, 2010 1:13:25 PM
package net.rujel.setup;


import java.util.Date;

import net.rujel.setup.components.Login;
import net.rujel.setup.components.Main;
import net.rujel.setup.components.NoAccess;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WODirectAction;


public class DirectAction extends WODirectAction {
	public DirectAction(WORequest request) {
		super(request);
	}

	public WOActionResults defaultAction() {
		String password = (String) System.getProperty("PASSWORD");
		String ips = (String) System.getProperty("ALLOWED_IPS");
		String originatingIPAddress = null;
		String[] IP_ADDRESS_KEYS = new String[] {"x-webobjects-remote-addr", "remote_addr"};
		for (int i = 0; (originatingIPAddress == null) && (i < IP_ADDRESS_KEYS.length); i++)
		{
			originatingIPAddress = request().headerForKey((String) IP_ADDRESS_KEYS[i]);
		}
		if(originatingIPAddress == null)
			originatingIPAddress = "10.10.10.10";
		if (ips != null) {
			String[] ip = ips.split(",");
			
			boolean ipFlag = false;
			for (int i = 0; i < ip.length; i++) {
				if (ip[i].endsWith(".")) {
					if (ip[i].equals(".")) {
						ipFlag = true;
						break;
					}
					//ip[i] = ip[i].substring(0, ip[i].length() - 2);
					if (originatingIPAddress.startsWith(ip[i])) {
						ipFlag = true;
						break;
					}
				}
				if (originatingIPAddress.equals(ip[i])) {
					ipFlag = true;
					break;
				}
			}
			if(!ipFlag) {
				System.out.println(new Date().toString() + ": No Access for user with IP: " + originatingIPAddress);
				return pageWithName(NoAccess.class.getName());
			}
		}
		if (password != null) {
			String wrPassword = request().stringFormValueForKey("password");
			if (wrPassword != null) {
				if (!wrPassword.equals(password)){
					System.out.println(new Date().toString() + ": Wrong password from user with IP: " + originatingIPAddress);
					return pageWithName(NoAccess.class.getName());
				}
			}
			else {
				return pageWithName(Login.class.getName());
			}
		}
		System.out.println(new Date().toString() + ": User with IP: " + originatingIPAddress + " logged in.");
		return pageWithName(Main.class.getName());
	}
}
